export const SELECT_DIGITAL_BUTTON = "SELECT_DIGITAL_BUTTON";
export const SELECT_OPERATION_BUTTON = "SELECT_OPERATION_BUTTON";
export const SELECT_RESULT_BUTTON = "SELECT_RESULT_BUTTON";
export const SELECT_CLEAN_ALL_BUTTON = "SELECT_CLEAN_ALL_BUTTON";
export const SELECT_CLEAN_LAST_CHARACTER_BUTTON = "SELECT_CLEAN_LAST_CHARACTER_BUTTON";